# Generated by Django 5.2.17 on 2026-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('address', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('email_name', models.CharField(blank=True, max_length=200)),
                ('quote_available', models.BooleanField(default=True)),
                ('invoice_available', models.BooleanField(default=True)),
                ('payment_received', models.BooleanField(default=True)),
                ('payment_reminder', models.BooleanField(default=True)),
                ('quote_template', models.TextField(blank=True)),
                ('invoice_template', models.TextField(blank=True)),
                ('payment_template', models.TextField(blank=True)),
                ('reminder_template', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.CharField(blank=True, max_length=20)),
                ('year_end', models.CharField(blank=True, max_length=20)),
                ('predefined_line_items', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='INV-', max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('auto_increment', models.BooleanField(default=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('due_days', models.PositiveIntegerField(default=30)),
                ('hide_adjust_field', models.BooleanField(default=False)),
                ('terms_conditions', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('admin_notices', models.BooleanField(default=True)),
                ('template', models.CharField(default='classic', max_length=50)),
                ('custom_css', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('currency_position', models.CharField(default='before', max_length=20)),
                ('thousand_separator', models.CharField(default=',', max_length=5)),
                ('decimal_places', models.PositiveIntegerField(default=2)),
                ('payment_page', models.BooleanField(default=True)),
                ('payment_footer', models.TextField(blank=True)),
                ('bank_details', models.TextField(blank=True)),
                ('generic_payment', models.BooleanField(default=True)),
                ('paypal_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PDFSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(default='classic', max_length=50)),
                ('custom_css', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='QUO-', max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('auto_increment', models.BooleanField(default=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('quote_validity', models.PositiveIntegerField(default=30)),
                ('hide_adjust_field', models.BooleanField(default=False)),
                ('terms_conditions', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('accepting_quotes', models.BooleanField(default=True)),
                ('accept_decline_settings', models.BooleanField(default=True)),
                ('admin_notices', models.BooleanField(default=True)),
                ('template', models.CharField(default='classic', max_length=50)),
                ('custom_css', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices_include_tax', models.BooleanField(default=False)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_name', models.CharField(default='GST', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TranslateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='English', max_length=50)),
                ('invoice_title', models.CharField(default='Invoice', max_length=100)),
                ('quote_title', models.CharField(default='Quotation', max_length=100)),
                ('client_label', models.CharField(default='Client', max_length=100)),
                ('subtotal_label', models.CharField(default='Subtotal', max_length=100)),
                ('tax_label', models.CharField(default='Tax', max_length=100)),
                ('total_label', models.CharField(default='Total', max_length=100)),
            ],
        ),
    ]
